---
groups:
  - name: bosh-google-stemcell
    jobs:
      - ubuntu-trusty-stemcell
      - centos-7-stemcell

  - name: ubuntu
    jobs:
      - ubuntu-trusty-stemcell

  - name: centos
    jobs:
      - centos-7-stemcell

jobs:
  - name: ubuntu-trusty-stemcell
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: false, get: bosh-src}

      - task: build-stemcell
        file: bosh-cpi-src/ci/stemcell/tasks/build-stemcell.yml
        privileged: true
        config:
          params:
            build_number:    3202
            os_name:         ubuntu
            os_version:      trusty
            os_image_bucket: bosh-os-images
            os_image_file:   bosh-ubuntu-trusty-os-image.tgz
            bucket_name:     {{google_stemcells_bucket_name}}

      - put: bosh-ubuntu-stemcells
        params:
          file: stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz
          predefined_acl: "publicRead"

      - put: bosh-ubuntu-raw-stemcells
        params:
          file: stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz
          predefined_acl: "publicRead"

      - put: bosh-ubuntu-light-stemcells
        params:
          file: stemcell/light-bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz
          predefined_acl: "publicRead"

  - name: centos-7-stemcell
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: false, get: bosh-src}

      - task: build-stemcell
        file: bosh-cpi-src/ci/stemcell/tasks/build-stemcell.yml
        privileged: true
        config:
          params:
            build_number:    3202
            os_name:         centos
            os_version:      7
            os_image_bucket: bosh-os-images
            os_image_file:   bosh-centos-7-os-image.tgz
            bucket_name:     {{google_stemcells_bucket_name}}

      - put: bosh-centos-stemcells
        params:
          file: stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz
          predefined_acl: "publicRead"

      - put: bosh-centos-raw-stemcells
        params:
          file: stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent-raw.tar.gz
          predefined_acl: "publicRead"

      - put: bosh-centos-light-stemcells
        params:
          file: stemcell/light-bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz
          predefined_acl: "publicRead"

resources:
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-google-cpi-boshrelease.git
      branch: master

  - name: bosh-src
    type: git
    source:
      uri: https://github.com/frodenas/bosh.git
      branch: google

  - name: bosh-ubuntu-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz

  - name: bosh-ubuntu-raw-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz

  - name: bosh-ubuntu-light-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz

  - name: bosh-centos-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz

  - name: bosh-centos-raw-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent-raw.tar.gz

  - name: bosh-centos-light-stemcells
    type: gcs-resource
    source:
      json_key: {{google_json_key_data}}
      bucket:   {{google_stemcells_bucket_name}}
      regexp:   light-bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz

resource_types:
  - name: gcs-request
    type: docker-image
    source:
      repository: frodenas/gcs-resource
