---
<%
director_uuid = "e7dc1dd8-90a8-4654-a1d2-3fa7691f1dc5"
vip_ip = "104.197.144.58"
common_password = "c1oudc0w"
deployment_name = "concourse"
%>
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
- name: concourse
  version: latest
- name: garden-linux
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: common
  stemcell: trusty
  networks: 
  - name: public
    default: [dns, gateway]
  - name: vip
    static_ips:
      - <%= vip_ip %>

  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: /
      basic_auth_username: concourse
      basic_auth_password: ofcourse

      postgresql_database: &atc_db atc

  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  vm_type: common
  stemcell: trusty
  persistent_disk_type: database
  networks: [{name: private}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: REPLACE_ME
        password: REPLACE_ME

- name: worker
  instances: 1
  vm_type: worker
  stemcell: trusty
  networks: [{name: private}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-linux
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
